CREATE TABLE "words" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"word" text,
	"recordId" integer
);
--> statement-breakpoint
ALTER TABLE "records" ADD COLUMN "order" integer;--> statement-breakpoint
ALTER TABLE "words" ADD CONSTRAINT "words_recordId_records_id_fk" FOREIGN KEY ("recordId") REFERENCES "public"."records"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "word" ON "words" USING btree ("word");--> statement-breakpoint
ALTER TABLE "records" DROP COLUMN "name";