CREATE TABLE "sentences" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sentences_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"recordId" integer,
	"gloss" text,
	"translation" text,
	"clip" text
);
--> statement-breakpoint
DROP INDEX "word";--> statement-breakpoint
ALTER TABLE "sentences" ADD CONSTRAINT "sentences_recordId_records_id_fk" FOREIGN KEY ("recordId") REFERENCES "public"."records"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "records" DROP COLUMN "order";